namespace ViceSharp.Abstractions;

/// <summary>
/// Full validation report generated by lockstep execution
/// </summary>
public sealed class ValidationReport
{
    public long TotalCyclesExecuted { get; init; }
    public long FirstMismatchCycle { get; init; }
    public bool Success => FirstMismatchCycle == -1;
    public StateDiff? Mismatch { get; init; }

    public static ValidationReport Pass(long cycles)
    {
        return new ValidationReport
        {
            TotalCyclesExecuted = cycles,
            FirstMismatchCycle = -1
        };
    }

    public static ValidationReport Fail(long cycles, long mismatchCycle, StateDiff diff)
    {
        return new ValidationReport
        {
            TotalCyclesExecuted = cycles,
            FirstMismatchCycle = mismatchCycle,
            Mismatch = diff
        };
    }
}