<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>HvscFetch</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpCompress" />
  </ItemGroup>
</Project>
